<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { monthlyReportRepo, type SavedReport } from '../repo/monthlyReport.repo'

const props = defineProps<{
  clientId: string
  clientName: string
}>()

const reports = ref<SavedReport[]>([])
const loading = ref(true)
const downloading = ref<string | null>(null) // month string being downloaded

const toast = ref<{ text: string; type: 'success' | 'error' } | null>(null)

function showToast(text: string, type: 'success' | 'error') {
  toast.value = { text, type }
  setTimeout(() => { toast.value = null }, 3500)
}

onMounted(async () => {
  try {
    reports.value = await monthlyReportRepo.listReports(props.clientId)
  } finally {
    loading.value = false
  }
})

function formatMonth(month: string) {
  const [y, m] = month.split('-')
  return new Date(Number(y), Number(m) - 1, 1).toLocaleDateString('en-US', {
    month: 'long',
    year: 'numeric',
  })
}

function formatDate(ts: string) {
  return new Date(ts).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })
}

async function download(report: SavedReport) {
  downloading.value = report.month
  try {
    await monthlyReportRepo.downloadReport(props.clientId, report.month, props.clientName, true)
    showToast('Report downloaded', 'success')
  } catch (e: any) {
    showToast(e?.message ?? 'Download failed', 'error')
  } finally {
    downloading.value = null
  }
}
</script>

<template>
  <div class="rounded-2xl border border-border bg-card p-5 sm:p-6 space-y-4">
    <!-- Toast -->
    <Transition name="fade">
      <div
        v-if="toast"
        :class="[
          'fixed bottom-6 right-6 z-50 rounded-xl px-5 py-3 text-sm font-semibold shadow-lg',
          toast.type === 'success' ? 'bg-primary text-white' : 'bg-destructive text-white',
        ]"
      >
        {{ toast.text }}
      </div>
    </Transition>

    <!-- Header -->
    <div class="flex items-center gap-3">
      <div class="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
      </div>
      <div>
        <h3 class="font-semibold text-foreground">Monthly Reports</h3>
        <p class="text-xs text-muted-foreground">Generated by your trainer</p>
      </div>
    </div>

    <!-- Loading -->
    <div v-if="loading" class="py-6 text-center text-sm text-muted-foreground">
      Loading...
    </div>

    <!-- Empty -->
    <div v-else-if="reports.length === 0" class="py-6 text-center">
      <p class="text-sm text-muted-foreground">No reports available yet.</p>
      <p class="text-xs text-muted-foreground mt-1">Your trainer will generate monthly progress reports here.</p>
    </div>

    <!-- List -->
    <div v-else class="divide-y divide-border">
      <div
        v-for="report in reports"
        :key="report.id"
        class="flex items-center justify-between gap-4 py-3"
      >
        <div class="flex items-center gap-3 min-w-0">
          <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/5 text-primary flex-shrink-0">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>

          <div class="min-w-0">
            <p class="font-semibold text-foreground text-sm">{{ formatMonth(report.month) }}</p>
            <p class="text-xs text-muted-foreground">{{ formatDate(report.generated_at) }}</p>
          </div>
        </div>

        <button
          @click="download(report)"
          :disabled="downloading === report.month"
          class="flex items-center gap-1.5 rounded-xl border border-border bg-background px-3 py-1.5 text-xs font-semibold text-foreground hover:bg-muted disabled:opacity-50 transition-colors flex-shrink-0"
        >
          <svg v-if="downloading !== report.month" xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          <svg v-else class="h-3.5 w-3.5 animate-spin" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
          </svg>
          {{ downloading === report.month ? 'Downloading...' : 'Download' }}
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active { transition: opacity 0.3s; }
.fade-enter-from,
.fade-leave-to { opacity: 0; }
</style>
